import { AttachmentBuilder } from 'discord.js';

export async function generateTranscript(channel, ticket) {
  const messages = await channel.messages.fetch({ limit: 100 });
  const sorted = [...messages.values()].reverse();

  const rows = sorted.map(msg => {
    const time = msg.createdAt.toLocaleString('id-ID');
    const author = msg.author.tag;
    const content = msg.content || '';
    const embeds = msg.embeds.map(e => `[EMBED: ${e.title || 'No Title'}]`).join(' ');
    return `<tr>
      <td class="time">${time}</td>
      <td class="author">${escapeHtml(author)}</td>
      <td class="content">${escapeHtml(content)} ${embeds}</td>
    </tr>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transcript - ${channel.name}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', sans-serif; background: #1a1a2e; color: #e0e0e0; padding: 20px; }
    h1 { color: #a855f7; margin-bottom: 8px; font-size: 1.5rem; }
    .meta { color: #888; font-size: 0.85rem; margin-bottom: 20px; }
    .meta span { margin-right: 16px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #16213e; color: #a855f7; padding: 10px 14px; text-align: left; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 1px; }
    tr:nth-child(even) { background: #16213e55; }
    td { padding: 8px 14px; vertical-align: top; font-size: 0.9rem; border-bottom: 1px solid #ffffff10; }
    .time { color: #888; white-space: nowrap; font-size: 0.8rem; width: 160px; }
    .author { color: #a855f7; font-weight: 600; white-space: nowrap; width: 180px; }
    .content { word-break: break-word; }
    .footer { margin-top: 16px; color: #555; font-size: 0.75rem; text-align: center; }
  </style>
</head>
<body>
  <h1>📋 Transcript: #${channel.name}</h1>
  <div class="meta">
    <span>👤 Buyer: ${ticket.buyerTag}</span>
    <span>💎 Robux: ${ticket.robuxAmount}</span>
    <span>💰 Total: Rp${ticket.totalPrice.toLocaleString('id-ID')}</span>
    <span>📅 Dibuat: ${new Date(ticket.createdAt).toLocaleString('id-ID')}</span>
  </div>
  <table>
    <thead><tr><th>Waktu</th><th>Pengirim</th><th>Pesan</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Transcript generated by Robux Bot • ${new Date().toLocaleString('id-ID')}</div>
</body>
</html>`;

  const buffer = Buffer.from(html, 'utf-8');
  return new AttachmentBuilder(buffer, { name: `transcript-${channel.name}.html` });
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
